GET https://libgen.li/json.php?object=e&isbn=9780698192157&addkeys=*

####
GET https://openlibrary.org/search.json?q=Ego%20Is%20the%20Enemy&sort=new

####
GET https://openlibrary.org/isbn/9780698192157